import React, { useState, useEffect } from 'react';
import confetti from 'canvas-confetti';
import { TRANSLATIONS } from '../data/translations';
import { SpeechService } from '../services/speechService';
import HotspotOverlay from './HotspotOverlay';
import ComparisonSlider from './ComparisonSlider';

export default function AnalysisResults({
  result,
  imageSrc,
  crop,
  currentLang,
  onReset,
  onOpenHealthCard,
  onSaveScan
}) {
  const [showHotspots, setShowHotspots] = useState(true);
  const [showComparison, setShowComparison] = useState(false);
  const [userRating, setUserRating] = useState(0);
  const [ratingSubmitted, setRatingSubmitted] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);

  const t = TRANSLATIONS[currentLang] || TRANSLATIONS.en;

  // Trigger celebration if plant is healthy!
  useEffect(() => {
    if (result?.severity === 'healthy') {
      confetti({
        particleCount: 60,
        spread: 70,
        origin: { y: 0.6 },
        colors: ['#4ade80', '#22c55e', '#86efac', '#c8a84b']
      });
    }
  }, [result]);

  if (!result) return null;

  const handleVoiceReadout = () => {
    if (isSpeaking) {
      SpeechService.stopSpeech();
      setIsSpeaking(false);
      return;
    }

    const readoutText = `${result.className}. Severity: ${result.severity}. ${result.desc}. Recommended treatment: ${result.remedies?.[0]?.steps?.[0] || 'See remedy list'}`;
    SpeechService.speak(
      readoutText,
      currentLang,
      () => setIsSpeaking(true),
      () => setIsSpeaking(false)
    );
  };

  const handleShareWhatsApp = () => {
    const text = `🌿 *Agrova AI Diagnosis Report*\n\n🌱 *Crop:* ${crop}\n🔍 *Disease:* ${result.className} (${result.latin || ''})\n📊 *Confidence:* ${(result.probability * 100).toFixed(1)}%\n⚠️ *Severity:* ${result.severity.toUpperCase()}\n\n📝 *Diagnosis:* ${result.desc}\n\n💊 *Primary Remedy:* ${result.remedies?.[0]?.steps?.[0] || 'See full treatment'}\n\n_Generated by Agrova AI Farming Assistant_`;
    const url = `https://wa.me/?text=${encodeURIComponent(text)}`;
    window.open(url, '_blank');
  };

  const handleRating = (stars) => {
    setUserRating(stars);
    setRatingSubmitted(true);
    setTimeout(() => setRatingSubmitted(false), 3000);
  };

  const severityColorMap = {
    high: { bg: '#fee2e2', border: '#fca5a5', text: '#991b1b', label: t.severityHigh },
    medium: { bg: '#fef3c7', border: '#fcd34d', text: '#92400e', label: t.severityMedium },
    low: { bg: '#f0fdf4', border: '#86efac', text: '#166534', label: t.severityLow },
    healthy: { bg: '#f0fdf4', border: '#4ade80', text: '#166534', label: t.severityHealthy }
  };

  const sevStyle = severityColorMap[result.severity] || severityColorMap.medium;

  return (
    <section style={{ position: 'relative', zIndex: 1, padding: '0 1.5rem', marginBottom: '50px' }}>
      <div className="glass-card" style={{ maxWidth: '880px', margin: '0 auto', padding: '2.4rem' }}>
        {/* Header Title & Confidence Pill */}
        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: '24px',
            flexWrap: 'wrap',
            gap: '12px'
          }}
        >
          <div>
            <h2 style={{ fontSize: '1.6rem', color: 'var(--green-deep)', fontWeight: 800 }}>
              {t.analysisResults}
            </h2>
            <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>
              Crop: <strong>{crop}</strong>
            </span>
          </div>

          <div
            style={{
              background: 'rgba(74, 145, 87, 0.12)',
              border: '1.5px solid rgba(74, 145, 87, 0.3)',
              color: 'var(--green-mid)',
              borderRadius: '50px',
              padding: '6px 16px',
              fontWeight: 800,
              fontSize: '0.88rem'
            }}
          >
            {(result.probability * 100).toFixed(1)}% {t.confidence}
          </div>
        </div>

        {/* Low confidence notice if < 65% */}
        {result.probability < 0.65 && (
          <div
            style={{
              background: '#fffbeb',
              border: '2px solid #f59e0b',
              borderRadius: '16px',
              padding: '1.2rem',
              marginBottom: '20px',
              display: 'flex',
              gap: '12px',
              alignItems: 'flex-start'
            }}
          >
            <span style={{ fontSize: '1.8rem' }}>⚠️</span>
            <div>
              <div style={{ fontWeight: 700, color: '#92400e', marginBottom: '4px' }}>
                {t.lowConfidenceTitle}
              </div>
              <div style={{ fontSize: '0.85rem', color: '#78350f', lineHeight: 1.5 }}>
                {t.lowConfidenceDesc}
              </div>
            </div>
          </div>
        )}

        {/* Disease Info Card with Hotspots Overlay */}
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
            gap: '24px',
            marginBottom: '24px',
            alignItems: 'start'
          }}
        >
          {/* Leaf with Hotspot Canvas */}
          <div>
            <HotspotOverlay
              imageSrc={imageSrc}
              hotspots={result.hotspots || []}
              showHotspots={showHotspots}
            />

            {result.hotspots && result.hotspots.length > 0 && (
              <div style={{ marginTop: '10px', display: 'flex', gap: '8px' }}>
                <button
                  className="btn btn-secondary"
                  onClick={() => setShowHotspots(!showHotspots)}
                  style={{ fontSize: '0.78rem', padding: '6px 14px' }}
                >
                  🎯 {showHotspots ? 'Hide Hotspots' : t.hotspotsToggle}
                </button>
                <button
                  className="btn btn-secondary"
                  onClick={() => setShowComparison(!showComparison)}
                  style={{ fontSize: '0.78rem', padding: '6px 14px' }}
                >
                  ⚖️ {showComparison ? 'Hide Comparison' : t.compareToggle}
                </button>
              </div>
            )}
          </div>

          {/* Disease Text Summary */}
          <div>
            <div
              style={{
                background: sevStyle.bg,
                border: `1.5px solid ${sevStyle.border}`,
                borderRadius: '18px',
                padding: '1.5rem'
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '8px' }}>
                <span style={{ fontSize: '2rem' }}>{result.icon || '🍃'}</span>
                <div>
                  <h3 style={{ fontSize: '1.35rem', color: sevStyle.text, fontWeight: 800 }}>
                    {result.className}
                  </h3>
                  <div style={{ fontSize: '0.8rem', fontStyle: 'italic', color: 'var(--text-muted)' }}>
                    {result.latin}
                  </div>
                </div>
              </div>

              <div
                style={{
                  display: 'inline-block',
                  background: sevStyle.text,
                  color: '#fff',
                  fontSize: '0.75rem',
                  fontWeight: 800,
                  padding: '3px 12px',
                  borderRadius: '50px',
                  marginBottom: '12px'
                }}
              >
                {sevStyle.label}
              </div>

              <p style={{ fontSize: '0.88rem', color: '#444', lineHeight: 1.65 }}>
                {result.desc}
              </p>
            </div>
          </div>
        </div>

        {/* Comparison Slider (if toggled) */}
        {showComparison && (
          <ComparisonSlider
            diseasedSrc={imageSrc}
            healthySrc={result.healthyReference}
            diseaseName={result.className}
          />
        )}

        {/* Recommended Remedies Grid */}
        <div style={{ marginTop: '28px', marginBottom: '28px' }}>
          <h3 style={{ fontSize: '1.2rem', color: 'var(--green-deep)', fontWeight: 800, marginBottom: '16px' }}>
            💊 {t.recommendedRemedies}
          </h3>

          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
              gap: '14px'
            }}
          >
            {result.remedies?.map((rem, idx) => (
              <div
                key={idx}
                style={{
                  background: 'rgba(245, 240, 232, 0.65)',
                  border: '1px solid #dde7de',
                  borderRadius: '14px',
                  padding: '1.2rem'
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '10px' }}>
                  <span style={{ fontSize: '1.2rem' }}>{rem.icon}</span>
                  <span style={{ fontWeight: 700, fontSize: '0.9rem', color: 'var(--green-deep)' }}>
                    {rem.title}
                  </span>
                </div>

                <ul style={{ listStyle: 'none', paddingLeft: 0 }}>
                  {rem.steps.map((step, sIdx) => (
                    <li
                      key={sIdx}
                      style={{
                        fontSize: '0.82rem',
                        color: '#555',
                        lineHeight: 1.5,
                        marginBottom: '6px',
                        paddingLeft: '16px',
                        position: 'relative'
                      }}
                    >
                      <span style={{ position: 'absolute', left: 0, color: 'var(--green-fresh)' }}>→</span>
                      {step}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>

        {/* Action Bar */}
        <div
          style={{
            display: 'flex',
            gap: '10px',
            flexWrap: 'wrap',
            paddingTop: '20px',
            borderTop: '1px solid var(--section-border)'
          }}
        >
          <button className="btn btn-secondary" onClick={onReset}>
            ↻ {t.tryAnother}
          </button>

          <button
            className="btn btn-primary"
            onClick={handleVoiceReadout}
            style={{ background: isSpeaking ? '#ef4444' : 'var(--green-deep)' }}
          >
            {isSpeaking ? '⏹ Stop Voice' : `🔊 ${t.listenVoice}`}
          </button>

          <button className="btn btn-green" onClick={onOpenHealthCard}>
            📄 {t.healthCard}
          </button>

          <button
            className="btn"
            onClick={handleShareWhatsApp}
            style={{ background: '#25D366', color: '#fff' }}
          >
            📲 {t.shareWhatsApp}
          </button>

          <button className="btn btn-secondary" onClick={onSaveScan}>
            💾 {t.saveScan}
          </button>
        </div>

        {/* Accuracy Feedback Rating */}
        <div
          style={{
            marginTop: '24px',
            padding: '14px',
            borderRadius: '12px',
            background: 'rgba(255, 255, 255, 0.65)',
            border: '1px solid var(--section-border)',
            textAlign: 'center'
          }}
        >
          <div style={{ fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-muted)', marginBottom: '8px' }}>
            Was this diagnosis accurate?
          </div>
          <div style={{ display: 'flex', justifyContent: 'center', gap: '8px', fontSize: '1.6rem' }}>
            {[1, 2, 3, 4, 5].map((star) => (
              <span
                key={star}
                onClick={() => handleRating(star)}
                style={{
                  cursor: 'pointer',
                  transition: 'transform 0.15s',
                  transform: userRating >= star ? 'scale(1.15)' : 'none'
                }}
              >
                {userRating >= star ? '⭐' : '☆'}
              </span>
            ))}
          </div>
          {ratingSubmitted && (
            <div style={{ fontSize: '0.82rem', color: 'var(--green-fresh)', fontWeight: 700, marginTop: '6px' }}>
              ✅ Thank you for your feedback!
            </div>
          )}
        </div>
      </div>
    </section>
  );
}
